language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - nightly
    - pypy
    - pypy3

install: |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.2" ]
    then
        pip install coverage==3.7.1
    else
        pip install coverage
    fi
    pip install -r requirements.txt

script: make coverage
