language: python

os:
    - osx
    - linux

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - pypy
    - pypy3

install: pip install coveralls

script: make coverage

after_script: coveralls
